# Generated by Django 5.0.6 on 2024-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peformances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpeformance',
            name='time_field',
            field=models.CharField(default='hh:mm:ss', help_text='Enter time in HH:MM:SS format', max_length=8),
        ),
    ]
