# Generated by Django 5.0.6 on 2024-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peformances', '0002_alter_userpeformance_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpeformance',
            name='time_field',
            field=models.CharField(default='00:00:00', help_text='Enter time in HH:MM:SS format', max_length=8),
        ),
    ]
