# Generated by Django 5.0.6 on 2024-06-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peformances', '0006_alter_userpeformance_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpeformance',
            name='content',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
